# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: LemonJobs's Blog 
email: 1191374186@qq.com
description: > # this means to ignore newlines until "baseurl:"
    LemonJobs's Blog
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://LemonJobs.github.io" # the base hostname & protocol for your site
github_username: LemonJobs

# Build settings
markdown: kramdown
